from __future__ import annotations

import argparse
import os
import re
import secrets
from pathlib import Path


ROOT = Path(__file__).resolve().parent
ENV_PATH = ROOT / "livekit.env"
YAML_TEMPLATE_PATH = ROOT / "livekit.yaml.template"
YAML_PATH = ROOT / "livekit.yaml"

_ENV_LINE_RE = re.compile(r"^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*?)\s*$")


def _strip_quotes(value: str) -> str:
    value = value.strip()
    if (value.startswith("'") and value.endswith("'")) or (
        value.startswith('"') and value.endswith('"')
    ):
        return value[1:-1]
    return value


def _parse_env_file(path: Path) -> dict[str, str]:
    out: dict[str, str] = {}
    if not path.exists():
        return out
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        m = _ENV_LINE_RE.match(line)
        if not m:
            continue
        key, value = m.group(1), m.group(2)
        out[key] = _strip_quotes(value)
    return out


def _guess_livekit_url() -> str:
    # Prefer WEBUI_URL from the current environment when present.
    webui_url = os.environ.get("WEBUI_URL", "").strip()
    if webui_url:
        if webui_url.startswith("https://"):
            return f"wss://{webui_url.removeprefix('https://')}/lk"
        if webui_url.startswith("http://"):
            return f"ws://{webui_url.removeprefix('http://')}/lk"

    # Fallback: this deployment's default hostname.
    return "wss://chat.uh-oh.wtf/lk"


def _atomic_write(path: Path, data: str, mode: int) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp_path = path.with_suffix(path.suffix + ".tmp")
    tmp_path.write_text(data, encoding="utf-8")
    os.chmod(tmp_path, mode)
    tmp_path.replace(path)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate self-hosted LiveKit config + env files (no secret output)."
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing deploy/livekit/livekit.env and deploy/livekit/livekit.yaml",
    )
    args = parser.parse_args()

    if not YAML_TEMPLATE_PATH.exists():
        raise SystemExit(f"Missing template: {YAML_TEMPLATE_PATH}")

    existing_env = _parse_env_file(ENV_PATH)
    api_key = existing_env.get("LIVEKIT_API_KEY", "").strip()
    api_secret = existing_env.get("LIVEKIT_API_SECRET", "").strip()

    if (ENV_PATH.exists() or YAML_PATH.exists()) and not args.force:
        # If both exist, do nothing.
        if ENV_PATH.exists() and YAML_PATH.exists():
            print("LiveKit config already present; nothing to do.")
            return 0

    if args.force or not api_key:
        api_key = f"owui{secrets.token_hex(8)}"
    if args.force or not api_secret:
        # urlsafe avoids whitespace and YAML quoting issues.
        api_secret = secrets.token_urlsafe(48)

    livekit_url = existing_env.get("LIVEKIT_URL", "").strip() or _guess_livekit_url()
    agent_name = existing_env.get("LIVEKIT_AGENT_NAME", "").strip() or "owui-voice"

    if args.force or not ENV_PATH.exists():
        env_data = "\n".join(
            [
                "# Auto-generated by deploy/livekit/setup_self_hosted.py",
                "# This file is sourced by the LiveKit portal + agent services.",
                "",
                f"LIVEKIT_URL='{livekit_url}'",
                f"LIVEKIT_API_KEY='{api_key}'",
                f"LIVEKIT_API_SECRET='{api_secret}'",
                f"LIVEKIT_AGENT_NAME='{agent_name}'",
                "",
                "# Optional overrides",
                "# LIVEKIT_LLM_MODEL='zai-glm-4.7'",
                "# LIVEKIT_STT_MODEL='ink-whisper'",
                "# LIVEKIT_STT_LANGUAGE='en'",
                "# LIVEKIT_TTS_MODEL='sonic-2'",
                "# LIVEKIT_TTS_VOICE='f786b574-daa5-4673-aa0c-cbe3e8534c02'",
                "",
            ]
        )
        _atomic_write(ENV_PATH, env_data, 0o600)

    template = YAML_TEMPLATE_PATH.read_text(encoding="utf-8")
    yaml_data = (
        template.replace("__LIVEKIT_API_KEY__", api_key).replace(
            "__LIVEKIT_API_SECRET__", api_secret
        )
        + ("\n" if not template.endswith("\n") else "")
    )
    _atomic_write(YAML_PATH, yaml_data, 0o600)

    print("Wrote deploy/livekit/livekit.env and deploy/livekit/livekit.yaml.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
